{config, ...}:
# Sonarr — TV management. Confined to the Mullvad netns so RSS/indexer
# traffic + TheTVDB lookups go through WireGuard.
#
# Root folder: /mnt/nas/media/library/tv (filled by the NAS mount in
# storage.nix; until the NAS lands the import path is broken — same
# staging-then-activate logic as everything else here).
#
# qBittorrent connection: Sonarr reaches qBittorrent at
# `http://127.0.0.1:8080` (both share the `mullvad` netns loopback).
# The reconciler in Phase 6 wires this up via the qBittorrent download
# client API; until then, expect the connection to be unconfigured.
#
# API key: generated by Sonarr on first boot and persisted in
# /var/lib/sonarr/.config/NzbDrone/config.xml. The Phase 6 reconciler
# reads it from there for cross-service wiring (Prowlarr → Sonarr sync,
# Seerr → Sonarr). Not deterministic-via-sops in this phase to avoid
# fighting with the module's StateDirectory ownership.
let
  port = 8989;
in {
  services.sonarr = {
    enable = true;
    openFirewall = false;
    # dataDir kept at default so StateDirectory = "sonarr" stays in play
    # (the module only sets StateDirectory when dataDir is the default).
  };

  # Static user — safe to merge extraGroups.
  users.users.sonarr.extraGroups = ["media"];

  # Persist Sonarr's state directory (DB, config.xml with the API key,
  # logs, backups). The downloads + library themselves are on /srv and
  # /mnt/nas/media respectively, so they're not in this list.
  environment.persistence."${config.hostSpec.persistFolder}".directories = [
    {
      directory = "/var/lib/sonarr";
      user = "sonarr";
      group = "sonarr";
      mode = "0700";
    }
  ];

  systemd.services.sonarr.vpnConfinement = {
    enable = true;
    vpnNamespace = "mullvad";
  };

  vpnNamespaces.mullvad.portMappings = [
    {
      from = port;
      to = port;
      protocol = "tcp";
    }
  ];

  networking.firewall.extraCommands = ''
    iptables -I nixos-fw -p tcp --dport ${toString port} -s 192.168.1.55 -j nixos-fw-accept
  '';
}
