keys:
  - &users
    - &sanfe age1dzpr70ksa4nvcjrt3amwxzs0vu7mr7wwupz7c7n0rcym5s937upsk0tyly
  - &hosts
    - &asgard age1z2v0al9d5g97c25vqw5kdan7upvyuhm9v9xjqa5fp6xvtjt7xens4hxq7m
    - &midgard age10krzdam0gl4a96k4sh40ew3mf4l75vyc2z2m454l49xap9pjhajqvmrjur
    - &bifrost age10qfc7fsd2ze6q29edssw55h5dpfhur8v7gqcrgy6lee4r8ylnassh0yg5v
    - &raidho age1t2cjnmj9tczrxn502q4wtp55unj5q9jxlwkunz9v3kduwczujc9sp7v8du
    - &draupnir age1fdsftvaxgpgpyxs8k6nkm5c2540njwk63nw7rlcwspr49mlnl96qj23p7l
creation_rules:
  - path_regex: hosts/common/secrets\.ya?ml$
    key_groups:
      - age:
          - *sanfe
          - *asgard
          - *midgard
          - *bifrost
          - *raidho
          - *draupnir
  - path_regex: hosts/asgard/secrets\.ya?ml$
    key_groups:
      - age:
          - *sanfe
          - *asgard
  - path_regex: hosts/bifrost/secrets\.ya?ml$
    key_groups:
      - age:
          - *sanfe
          - *bifrost
  - path_regex: hosts/draupnir/secrets\.ya?ml$
    key_groups:
      - age:
          - *sanfe
          - *draupnir
